.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH capabilities 1  "capabilities " 
.SH NAME
capabilities \- Show capabilities and supported features
.SH SYNOPSIS
\fBcapabilities\fR [\fB\-\-profile\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show capabilities and supported features
.SH OPTIONS
.TP
\fB\-\-profile\fR \fI<PROFILE>\fR [default: native\-v1]
Profile for capabilities output
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
