.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH claim 1  "claim " 
.SH NAME
claim \- Claim an issue from the ready frontier
.SH SYNOPSIS
\fBclaim\fR <\fB\-\-assignee\fR> [\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Claim an issue from the ready frontier
.SH OPTIONS
.TP
\fB\-\-assignee\fR \fI<ASSIGNEE>\fR
Assignee name (required)
.TP
\fB\-\-json\fR
Output in JSON format
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
