.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH close 1  "close " 
.SH NAME
close \- Close an issue
.SH SYNOPSIS
\fBclose\fR <\fB\-\-reason\fR> [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> 
.SH DESCRIPTION
Close an issue
.SH OPTIONS
.TP
\fB\-\-reason\fR \fI<REASON>\fR
Close reason (required)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>
Issue ID
