.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH doctor 1  "doctor " 
.SH NAME
doctor \- Diagnose workspace integrity and optionally perform repairs
.SH SYNOPSIS
\fBdoctor\fR [\fB\-\-repair\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Diagnose workspace integrity and optionally perform repairs
.SH OPTIONS
.TP
\fB\-\-repair\fR
Attempt automatic repairs
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
