.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH init 1  "init " 
.SH NAME
init \- Initialize a new workspace
.SH SYNOPSIS
\fBinit\fR [\fB\-\-prefix\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Initialize a new workspace
.SH OPTIONS
.TP
\fB\-\-prefix\fR \fI<PREFIX>\fR [default: bead]
Custom prefix for bead IDs (default: bead)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
