.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH label 1  "label " 
.SH NAME
label \- Manage labels
.SH SYNOPSIS
\fBlabel\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Manage labels
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
label\-add(1)
Add a label to an issue
.TP
label\-remove(1)
Remove a label from an issue
.TP
label\-help(1)
Print this message or the help of the given subcommand(s)
