.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH list 1  "list " 
.SH NAME
list \- List issues
.SH SYNOPSIS
\fBlist\fR [\fB\-\-json\fR] [\fB\-\-status\fR] [\fB\-\-assignee\fR] [\fB\-\-ready\fR] [\fB\-\-comments\fR] [\fB\-\-limit\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List issues
.SH OPTIONS
.TP
\fB\-\-json\fR
Output in JSON format
.TP
\fB\-\-status\fR \fI<STATUS>\fR
Filter by status
.TP
\fB\-\-assignee\fR \fI<ASSIGNEE>\fR
Filter by assignee
.TP
\fB\-\-ready\fR
Show only ready frontier issues
.TP
\fB\-\-comments\fR \fI<COMMENTS>\fR [default: none]
Comment projection: none, unresolved, or all (default: none)
.TP
\fB\-\-limit\fR \fI<LIMIT>\fR [default: 100]
Maximum number of issues to return (0\-999999)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
